sim_scene.image_on_detector[1].header['CFAMNAME'] = '3F'
sim_scene.image_on_detector[1].header['DPAMNAME'] = 'PUPIL'
sim_scene.image_on_detector[1].header['LSAMNAME'] = 'OPEN'
sim_scene.image_on_detector[1].header['FSAMNAME'] = 'OPEN'
sim_scene.image_on_detector[1].header['FPAMNAME'] = 'OPEN_12'
